# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20171111_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='current_predictions',
            old_name='Call_counts',
            new_name='call_counts',
        ),
        migrations.RenameField(
            model_name='predictions',
            old_name='Call_counts',
            new_name='call_counts',
        ),
        migrations.AddField(
            model_name='current_emscall',
            name='addr',
            field=models.CharField(default='111 Post Street, San Francisco CA', max_length=200),
        ),
    ]
