# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20171117_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='ems_calls',
            name='addr',
            field=models.CharField(default=1111, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='current_emscall',
            name='addr',
            field=models.CharField(max_length=200),
        ),
    ]
