# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20171117_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_ambulance',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
    ]
