# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20171117_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=10)),
                ('event_desc', models.CharField(max_length=80)),
                ('unit', models.IntegerField()),
                ('LAT', models.FloatField()),
                ('LONG', models.FloatField()),
            ],
        ),
    ]
