# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_event_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_feed',
            name='LAT',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='event_feed',
            name='LONG',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='event_feed',
            name='unit',
            field=models.IntegerField(null=True),
        ),
    ]
