# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_current_ambulance_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_ambulance',
            name='time',
        ),
    ]
